---
- name: Send slack message
  hosts: localhost
  connection: local
  gather_facts: true
  run_once: true

  tasks:
  - name: Send notification message via Slack
    community.general.slack:
      token: TD303K6MD/B02GAFSTE3V/whz0tbeoxFz10a092Jkpo6nO
      msg: '{{ message }} {{ cluster_deployment | to_nice_json }} {{ install_config | to_nice_json }}'
    delegate_to: localhost
