---
- name: Send slack message
  hosts: localhost
  connection: local
  gather_facts: true
  run_once: true

  tasks:
  - name: Send notification message via Slack
    community.general.slack:
      token: TD303K6MD/B0271QF0CJ2/9G3xqi1x1Mf3O9n8fOVIsO99
      msg: '{{ message }} \n {{ cluster_deployment | to_nice_json }} \n {{ install_config | to_nice_json }}'
    delegate_to: localhost
